import { contracts } from '@/configs/contracts'
import { tokens } from '@/configs/tokens'
import { PoolName } from '@/types'

export const INT_MIN =
  '57896044618658097711785492504343953926634992332820282019728792003956564819968'

const getGraphUrl = (name: string) => {
  return `http://13.228.107.16:8000/subgraphs/name/${name}`
}

export const pools = {
  wstETH: {
    isShort: false,
    poolName: PoolName.wstETH,
    deltaCollAddress: tokens.wstETH,
    deltaDebtAddress: tokens.fxUSD,
    deltaCollSymbol: 'wstETH',
    deltaDebtSymbol: 'fxUSD',
    poolAddress: contracts.WstETHLongPool,
    oracle: contracts.PriceOracle_StETHPriceOracle,
    creditNote: contracts.CreditNote_wstETH,
    baseTokenSymbol: 'wstETH',
    lsdTokenSymbol: 'ETH',
    marketSymbol: 'ETH',
    collSymbol: 'ETH', // stETH
    zapSymbol: 'stETH',
    debtSymbol: 'fxUSD',
    decimals: 18,
    minPrecision: 1e14,
    precision: 1e18,
    creditNoteSymbol: 'fxETH',
    graphUrl: getGraphUrl('fx-v2-wsteth'),
  },
  WBTC: {
    isShort: false,
    poolName: PoolName.WBTC,
    deltaCollAddress: tokens.WBTC,
    deltaDebtAddress: tokens.fxUSD,
    deltaCollSymbol: 'WBTC',
    deltaDebtSymbol: 'fxUSD',
    poolAddress: contracts.WBTCLongPool,
    oracle: contracts.PriceOracle_WBTCPriceOracle,
    creditNote: contracts.CreditNote_WBTC,
    baseTokenSymbol: 'wBTC',
    lsdTokenSymbol: 'WBTC',
    marketSymbol: 'BTC',
    collSymbol: 'WBTC',
    zapSymbol: 'WBTC',
    debtSymbol: 'fxUSD',
    decimals: 8,
    minPrecision: 1e12,
    precision: 1e8,
    creditNoteSymbol: 'fxBTC',
    graphUrl: getGraphUrl('fx-v2-wbtc'),
  },
  wstETH_short: {
    isShort: true,
    poolName: PoolName.wstETH_short,
    deltaCollAddress: tokens.fxUSD,
    deltaDebtAddress: tokens.wstETH,
    deltaCollSymbol: 'fxUSD',
    deltaDebtSymbol: 'wstETH',
    poolAddress: contracts.WstETHShortPool,
    oracle: contracts.PriceOracle_InverseWstETHPriceOracle,
    creditNote: contracts.CreditNote_wstETH,
    baseTokenSymbol: 'wstETH',
    lsdTokenSymbol: 'ETH',
    marketSymbol: 'ETH',
    collSymbol: 'fxUSD',
    zapSymbol: 'fxUSD',
    debtSymbol: 'wstETH',
    decimals: 18,
    minPrecision: 1e14,
    precision: 1e18,
    creditNoteSymbol: 'fxETH',
    graphUrl: getGraphUrl('fx-v2-wsteth-short'),
  },
  WBTC_short: {
    isShort: true,
    poolName: PoolName.WBTC_short,
    deltaCollAddress: tokens.fxUSD,
    deltaDebtAddress: tokens.WBTC,
    deltaCollSymbol: 'fxUSD',
    deltaDebtSymbol: 'WBTC',
    poolAddress: contracts.WBTCShortPool,
    oracle: contracts.PriceOracle_InverseWBTCPriceOracle,
    creditNote: contracts.CreditNote_WBTC,
    baseTokenSymbol: 'wBTC',
    lsdTokenSymbol: 'WBTC',
    marketSymbol: 'BTC',
    collSymbol: 'fxUSD',
    zapSymbol: 'fxUSD',
    debtSymbol: 'WBTC',
    decimals: 8,
    minPrecision: 1e12,
    precision: 1e8,
    creditNoteSymbol: 'fxBTC',
    graphUrl: getGraphUrl('fx-v2-wbtc-short'),
  },
}
